### ISSUE TITLE
Atividade 3 - Questão 3

### ISSUE THREAD

**Issue by alanvasconcelos** [professorgilzamir/pythoncourse#19]
"A função deve fazer o unpacking de kargs e, para cada par column=type, deve **interpretar** a valor corresponde da coluna com nome column como sendo do tipo indicado por type".

Professor o que seria esse interpretar que a função terá que fazer?

**Comment by thiagormagalhaes** [comment]
Acho que seria converter. A tupla que é recebida pela função interpreta tudo como string mas a colunas em que o valor é um inteiro... o interpretar seria fazer a conversão de acordo com o tipo indicado em kargs.

**Comment by professorgilzamir** [comment]
O Thiago está certo.

**Comment by professorgilzamir** [comment]
Como a questão foi resolvida, esta issue será fechada.
