### ISSUE TITLE
src/utils.extract_file name fail when try extract file name with more one dot.

### ISSUE THREAD

**Issue by professorgilzamir** [professorgilzamir/pythoncourse#2]
Function src/utils.extract_filename fail when try extract file name with more one dot. For example: when applied to "my.file.txt", extract_filename function returns "my", but correct output is "my.file.

**Comment by gilzamir** [comment]
Qual o prazo para conclusão dessa issue?

**Comment by professorgilzamir** [comment]
This bug has been fixed by Thiago Magalhães.
